# Generated by Django 5.1.1 on 2024-09-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_id', models.IntegerField()),
                ('module_name', models.CharField(max_length=20)),
                ('total_marks', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
