# Generated by Django 5.1.1 on 2024-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking_scheme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markingscheme',
            name='module_name',
            field=models.CharField(max_length=30),
        ),
    ]
