# Generated by Django 5.1.1 on 2024-09-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking_scheme', '0002_alter_markingscheme_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markingscheme',
            name='module_name',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
